version: '0.1'

services:
  supertokens-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_MYSQL_ROOT_PASSWORD
      MYSQL_USER: YOUR_MYSQL_USER
      MYSQL_PASSWORD: YOUR_MYSQL_PASSWORD
      MYSQL_DATABASE: YOUR_MYSQL_DATABASE
    ports:
      - 3306:3306
    networks:
      - overlay-network
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql_data:/var/lib/mysql

  supertokens-core:
    image: registry.supertokens.io/supertokens/supertokens-mysql:9.0
    depends_on:
      supertokens-db:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://YOUR_MYSQL_USER:YOUR_MYSQL_PASSWORD@supertokens-db:3306/YOUR_MYSQL_DATABASE
    networks:
      - overlay-network
    restart: no
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  overlay-network:
    driver: overlay
    #attachable: true
    external: true
